sandbox_mode = "workspace-write"
approval_policy = "on-request"
approvals_reviewer = "auto_review"

notify = ["/Users/codeminer/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
model = "gpt-6-sol"
model_reasoning_effort = "high"

[projects."/Users/codeminer/workstation/stockrobbers/smart-contract"]
trust_level = "trusted"

[projects."/Users/codeminer/workstation/dotfiles"]
trust_level = "trusted"

[plugins."app-6a9a3581fe6c8191b68b1b2d38f37dfd@openai-curated-remote"]
enabled = false

[plugins."browser-act@openai-curated-remote"]
enabled = false

[tui]
screen_reader_detection_done = true

[tui.model_availability_nux]
gpt-6-astra = 1
